### ISSUE TITLE
Recreate community and continue fwbuilder development

### ISSUE THREAD

**Issue by sirius** [sirius/fwbuilder-uninett#15]
@stevec99 @rolffokkens @antaflos @Jamin7777 @a-schild @xlordz @Magissia @runesyd @knumor @captbrando @bizonix @pmoetteli

Hi, all. I'm tagging you  because you have either contributed code, bug reports or shown interest in fwbuilder in some other way.

As you can see in https://github.com/UNINETT/fwbuilder/pull/10#issuecomment-217565230 the UNINETT fork has been dead for some time. I quit working for UNINETT last year, but I know they have had interest in keeping the project alive, and they have been looking for developers and/or users in the community. In the middle of June (this year) I'm finally done with my studies, and I'm interested in bringing this project back to life. I have much experience with Qt, and I know a lot of the fwbuilder codebase through my time at UNINETT.

We need to gather forces and (re)create the fwbuilder community. Both users contributing bugs reports and ideas/feature requests, and developers contributing code, documentation and advice.

**Comment by stevec99** [comment]
I'm not a programmer, always wanted to be but it never quite happened (I was quite good when at Uni many many years ago). However I'm willing to learn (CCIE finally out the way and I'm looking for something new to get stuck in to). There is nothing close to fwbuilder out there, let's make this happen.

I'm in :)


--
Steven Coutts
stevec@couttsnet.com

**Comment by rolffokkens** [comment]
fwbuilder deserves to be used and maintained, so I am definitely in favour! But some expectation management is in place: my contributions have been and will be limited though to fixing issues I'm running into myself, just because of serious time constraints. Having said that, excellent initiatitive!

**Comment by a-schild** [comment]
I would also contribute to the project. C++ isn't my world anymore, but I can help with bug tracking and all the other things which are needed for a project.

**Comment by captbrando** [comment]
Can do some basic coding, but probably not enterprise class. I’m available to help with documentation, testing and bug reports, and use cases.

Regards,

Branden R. Williams, DBA, CISSP, CISM
brw@brandenwilliams.com
Phone: +1 (214) 727-8227

http://www.brandenwilliams.com/

**Comment by Jamin7777** [comment]
Great project and the only open source system available for managing and maintaining firewall rulesets across multiple devices.

I only use it for linux firewalls - iptables, but the scope for different devices is broad.  Does this come with additional burden for maintaining the software?

Do other people use fwbuilder for Cisco or HP devices any longer?  
What use cases are most common?

I will assist where possible with testing and reporting

**Comment by a-schild** [comment]
I use fwbuilder only for linux systems (Mostly Debian, some Ubuntu and a few CentOS)

**Comment by carlxvier** [comment]
Hi.
I'm glad to hear that there are people wanting to keep on Firewall Builder maintenance and development.
I'm not a skilled codder but I have been using Firewall Builder for a long time and can relp on testing it on Linux.

Right now I'm running it on openSUSE Leap 4.2 with kernel 4.1.15-8-default and iptables-1.4.21-4.1.x86_64 
I already found 2 minor bugs related to the Linux compiler, they are going to be posted at the bug track.

**Comment by stevec99** [comment]
Mainly iptables for me, but can do testing on ASA and various Cisco devices.

I'm on mac, i need to get a build environment setup, any pointers would 
be good!

**Comment by sirius** [comment]
Thank you for great feedback. This looks promising. :)

@Jamin7777 The code for different devices is split between a common compiler code, and platform specific libraries and files. Fixing bugs in platform code is a bit easier than when the bug is found in shared code. In the latter case you might introduce bugs into other platforms, so you need more and wider testing. As for the most common use cases, I don't know. In Norway some universities are using at least Cisco and maybe some Juniper devices.

@stevec99 Homebrew and https://github.com/sirius/fwbuilder/blob/master/build_mac.sh will get you almost all the way on OSX. You'll need at least automake, libxml2, libxslt and zlib in addition to Qt. The script needs some updates for newer Xcode. I have a few patches ready, but I need to recreate my build system and test before I push.

**Comment by sirius** [comment]
I've sent @BrendanThompson a mail, asking about moving the community and upstream repository to @fwbuilder.

**Comment by BrendanThompson** [comment]
Have sent through a reply to @sirius

**Comment by sirius** [comment]
Development - upstream - is moved to https://github.com/fwbuilder/fwbuilder. Please retarget issues and pull requests to the new location.

**Comment by stevec99** [comment]
Hi all,

I've had to rebuild my mac and have lost the binary for this, could 
someone remind me where I can download from?

I only have the windows binary, and need to add a NAT, but it still has 
the NAT bug :(

Regards
